/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "Algorithms"

File("$rootDir").listFiles { dir, name ->
    (name.equals("library") || name.equals("test") || name.equals("benchmark")) && File(dir, name).isDirectory
}!!.forEach {
    val moduleName = it.name
    include(moduleName)
    it.list { dir, name -> File(dir, name).isDirectory && name != "build" }!!.forEach {
        include("$moduleName:$it")
    }
}